In [1]:
import preprocessing
import numpy as np

In [2]:
data = preprocessing.get_dataset()

Loading data sets
Empty file, skipping...
Empty file, skipping...
Empty file, skipping...
Empty file, skipping...
Empty file, skipping...
Empty file, skipping...
Empty file, skipping...
Empty file, skipping...
Data incomplete, skipping...
Empty file, skipping...
Empty file, skipping...
Empty file, skipping...
Empty file, skipping...
Empty file, skipping...
Empty file, skipping...
Empty file, skipping...
Empty file, skipping...
Empty file, skipping...
Empty file, skipping...
Empty file, skipping...
Empty file, skipping...
Empty file, skipping...
Empty file, skipping...
Empty file, skipping...
Empty file, skipping...
Empty file, skipping...
Empty file, skipping...
Empty file, skipping...
Empty file, skipping...
Empty file, skipping...
Empty file, skipping...
Empty file, skipping...
Empty file, skipping...
Empty file, skipping...
Empty file, skipping...
Empty file, skipping...
Empty file, skipping...
Empty file, skipping...
Empty file, skipping...
Empty file, skipping...
Empty file, skipp

NameError: name 'feat' is not defined

In [ ]:
data['y_train']['state_diff'].shape

In [6]:
x = np.array([[1,2,3,4]])
diffs = np.tile(x,(len(x),1))-np.tile(x.T,(1,len(x)))
print(diffs**2)

[[0 1 4 9]
 [1 0 1 4]
 [4 1 0 1]
 [9 4 1 0]]


In [3]:
a = {'i':1,'l':2}

In [6]:
type(a) == dict

True